<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE superheroes [
  <!ELEMENT superheroes ((superheroe | supervillano | monstruo)*)>
  <!ELEMENT superheroe ANY>
  <!ELEMENT supervillano ANY>
  <!ELEMENT monstruo ANY>
]>
<superheroes>
	<superheroe>Iron Man</superheroe>
	<supervillano>Thanos</supervillano>
	<supervillano>Thanos</supervillano>
	<supervillano>Thanos</supervillano>
	<monstruo>Monster kripton</monstruo>
	<supervillano>Thanos</supervillano>
</superheroes>