<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE placas [
  <!ELEMENT placas (placa)*>
  <!ELEMENT placa (microprocesador?, memoria?, modelo?, fabricante?)*>
  <!ELEMENT microprocesador (#PCDATA)>
  <!ELEMENT memoria (#PCDATA)>
  <!ELEMENT modelo (#PCDATA)>
  <!ELEMENT fabricante (asus | intel)>
  <!ELEMENT asus EMPTY>
  <!ELEMENT intel EMPTY>
]>
<placas>
  <placa>
    <memoria>4 GB</memoria>
    <microprocesador>i3</microprocesador>
    <modelo>5876 i 60</modelo>
    <fabricante><asus/></fabricante>
  </placa>
  <placa>
    <microprocesador>i5</microprocesador>
    <memoria>4 GB</memoria>
    <modelo>5878 i 60</modelo>
    <fabricante><intel/></fabricante>
  </placa>
</placas>