=== rafaelMunoz77/LMSGI/src/Unidad_04_DTD_XSD/DTD/examen2018/simpsons.dtd
<!NOTATION JPG SYSTEM "image/jpeg">
<!NOTATION GIF SYSTEM "image/gif">
<!NOTATION PNG SYSTEM "image/png">

<!ELEMENT springfield (adultos, ninios, temporadas?)>
<!ENTITY % estadoDeSpringfield "estado CDATA #FIXED 'Utah'">
<!ATTLIST springfield %estadoDeSpringfield;>
<!ELEMENT adultos (adulto*)>
<!ELEMENT adulto EMPTY>
<!ENTITY % caracteristicasPersonaje "nombre ID #REQUIRED 
                                colorPelo CDATA #IMPLIED
                                parentesco IDREFS #IMPLIED"> 
<!ATTLIST adulto %caracteristicasPersonaje; 
                casadoCon IDREF #IMPLIED
                imagen NOTATION (GIF | JPG | PNG) #IMPLIED>
<!ELEMENT ninios (ninio+)>
<!ELEMENT ninio EMPTY>
<!ATTLIST ninio %caracteristicasPersonaje;>
<!ENTITY groening "Matt Groening">
<!ELEMENT temporadas (#PCDATA | temporada)*>
<!ELEMENT temporada EMPTY>
<!ATTLIST temporada numero (1|2|3|4|5|6) #REQUIRED 
                    fechaInicio CDATA #REQUIRED>

=== rafaelMunoz77/LMSGI/src/Unidad_04_DTD_XSD/DTD/examen2018/simpsons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE springfield SYSTEM "simpsons.dtd">
<springfield estado="Utah">
    <adultos>
        <adulto nombre="Homer" colorPelo="Moreno" casadoCon="Marge" parentesco="Bart Lisa"/>
        <adulto nombre="Marge" colorPelo="Azul"/>
    </adultos>
    <ninios>
        <ninio nombre="Bart" colorPelo="Amarillo"/>
        <ninio nombre="Lisa" colorPelo="Amarillo" parentesco="Bart Marge Homer"/>
    </ninios>
    <temporadas>LLevamos un a√±o sin nueva temporada de &groening;
        <temporada numero="1" fechaInicio="15/08/1987"/>
        <temporada numero="2" fechaInicio="15/03/1989"/>
    </temporadas>
</springfield>
