=== rafaelMunoz77/LMSGI/src/Unidad_04_DTD_XSD/DTD/examen2017/arbolesYFrutas.dtd
<!ELEMENT arbolesYFrutas (arbol+, agricultor*, zona*, trabajo*)>
<!ELEMENT arbol (fruta, semilla?)>
<!ELEMENT fruta (#PCDATA | epocaRecogida)*>
<!ELEMENT semilla (#PCDATA)>
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ENTITY flores "Este Ã¡rbol tiene unas flores muy bonitas">
<!ATTLIST arbol %atributoNombre;
				tipoHoja (caduca | perenne) #IMPLIED 
				colorHoja CDATA #FIXED "verde">
<!ELEMENT epocaRecogida EMPTY>
<!ATTLIST epocaRecogida %atributoNombre;>
<!ELEMENT agricultor EMPTY>
<!ATTLIST agricultor nombre ID #REQUIRED>
<!ELEMENT zona (#PCDATA)>
<!ATTLIST zona agricultorResponsable IDREF #REQUIRED>
<!ELEMENT trabajo EMPTY>
<!ATTLIST trabajo agricultores IDREFS #REQUIRED>

=== rafaelMunoz77/LMSGI/src/Unidad_04_DTD_XSD/DTD/examen2017/arbolesYFrutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arbolesYFrutas SYSTEM "arbolesYFrutas.dtd">
<arbolesYFrutas>
	<arbol nombre="Naranjo" tipoHoja="perenne" colorHoja="verde">
		<fruta>Naranja
			<epocaRecogida nombre="invierno"/>
		</fruta>
		<semilla>SÃ­</semilla>
	</arbol>
	<arbol nombre="Olivo" tipoHoja="perenne">
		<fruta>Aceituna &flores;
			<epocaRecogida nombre="invierno"/>
		</fruta>
	</arbol>
	<agricultor nombre="Rafa"/>
	<agricultor nombre="Carmen"/>
	<zona agricultorResponsable="Rafa">Norte</zona>
	<trabajo agricultores="Rafa Carmen"/>
</arbolesYFrutas>
